apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Values.api.name .Values.deployment.environment }}
type: Opaque
data:
  API_DB_USER: {{ .Values.secrets.db_user }} 
  API_DB_PASSWORD: {{ .Values.secrets.db_pass }}