apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Values.api.name .Values.deployment.environment }}
  labels:
    service: {{ .Values.api.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
    name: web
  selector:
    app: {{ printf "%s-%s" .Values.api.name .Values.deployment.environment }}